### ISSUE TITLE
how to make ply to obj or fbx？

### ISSUE THREAD

**Issue by xwan07017** [alvinliu0/HumanGaussian#3]
hello，when i cmd launch.py ，i got a file of ply, but i want to show the file to blender or maya, could u give me some advise? 
thanks!

**Comment by ashawkey** [comment]
@xwan07017 Hi, we export 3D Gaussians instead of meshes, which need a special renderer and cannot be directly imported into blender. You may check these [available renderers](https://github.com/MrNeRF/awesome-3D-gaussian-splatting#open-source-implementations), including web renderers and unity plugins.

**Comment by silence-tang** [comment]
Hi, may I ask how to export mesh from trained 3DGS? Thanks a lot!
