### ISSUE TITLE
lauch init takes too long to finish

### ISSUE THREAD

**Issue by xh38** [alvinliu0/HumanGaussian#9]
100000 points' initialization takes more than 20 minutes on a RTX4090. Is it normal?

**Comment by oneThousand1000** [comment]
The [CodeSnapshotCallback](https://github.com/alvinliu0/HumanGaussian/blob/28a4d39b92dff9e9a9c11f53594fe26e5299018b/threestudio/utils/callbacks.py#L60) seems try to save all the files in this project. Consequently, as the number of generated results increases, files have been recursively duplicated, causing an exponential accumulation of data and time...

**Comment by xh38** [comment]
true dude @oneThousand1000

**Comment by oneThousand1000** [comment]
Maybe need to add a `.gitignore` file?

**Comment by alvinliu0** [comment]
Hi, many thanks for your interest in our work:)

Yes, this problem is indeed caused by forgetting to add a `.gitignore` file into this repo, which makes the code copying [callback](https://github.com/alvinliu0/HumanGaussian/blob/main/threestudio/utils/callbacks.py#L60) always replicating all the files under this repository. And sincerely thank @oneThousand1000 for giving advice and @xh38 for pointing out this:)

Best,

**Comment by GUI0809** [comment]
> true dude @oneThousand1000

Hello? I have the same problem as you. Can you provide the specific solution？Thanks！

**Comment by oneThousand1000** [comment]
> > true dude @oneThousand1000
> 
> Hello? I have the same problem as you. Can you provide the specific solution？Thanks！

A simple solution is to delete the CodeSnapshotCallback here:

https://github.com/alvinliu0/HumanGaussian/blob/84ef6918c04cea4374cb75d394e9bf58f2f5ca4e/launch.py#L126C13-L126C33
